---
title: "Introduction to ColourblindR"
author: "Ian Flores,Hayley Boyce,Sabrina K.Tse"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to ColourblindR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE,include = FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
  
)
```

ColourblindR: colourblind-friendly themes for ggplot2
====================================

[ColourblindR](https://github.com/UBC-MDS/ColourblindR) is a brand new theme package implemented for ggplot2 to optimize graphs into a format interpretable by people with colourblindness. Colourblindness, also known as colour vision deficiency, is a condition that affects individuals how they perceive colours visually. According to colourblindawareness.org, colourblindness affects 1 in every 12 men and 1 in every 200 women globally. The package is inspired by the fact that people without knowledge about this condition don't know how to make their graphs accesible. Our objective is to enhance data visualization by implementing proper colours so that the graphs are perceived correctly by all readers as intended.

As of March 3rd 2019,three themes are available in the `ColourblindR` package for the three most prevalent colourblind perspectives - protanopia, deuteranopes and tritanopes. 

`ColourblindR` functions
---------------------------------
Just like `theme_bw()` in the `ggplot2` package, the `ColourblindR` functions are to be used on top of `ggplot2` objects. The following theme functions modify the colour of geometric objects (points, lines, etc) and the layout of the plot:

* `theme_deutera()`:This function implements a theme that makes plots accesible to people with deuteranopia. The colour palette contains shades of yellow,gray and blue.

* `theme_prota()`:This function implements a theme that makes plots accesible to people with protanopia. The colour palette also contains shades of yellow,gray and blue, but sharper and warmer than theme_deutera().

* `theme_trita()`:This function implements a theme that makes plots accesible to people with  tritanopia. The colour palette contains shades of green,gray and pink.
